#!/bin/bash

#SBATCH --job-name=tensorflowShowandTell${SLURM_ARRAY_TASK_ID}
#SBATCH --mail-user=thpaul@nps.edu
#SBATCH --mail-type=ALL
#SBATCH --time=1:00:00

# To run as an array job, use the following command:
# sbatch --partition=beards --gres=gpu:1 --array=0-0 --mem=8192 --constraint=intel showAndTellClassify.sh
# squeue --user thpaul

#Directory containing images with *.jpg or format to classsify:
IMAGE_DIR="/work/thpaul/tf_tools/tensorflow/im2txt/myImages/*.jpg"

# Directory containing model checkpoints.
CHECKPOINT_DIR="/work/thpaul/tf_tools/tensorflow/im2txt/im2txt/model/train"

# Vocabulary file generated by the preprocessing script.
VOCAB_FILE="/work/thpaul/tf_tools/tensorflow/im2txt/im2txt/data/mscoco/word_counts.txt"

# Build the inference binary.
bazel build -c opt im2txt/run_inference

# Ignore GPU devices (only necessary if your GPU is currently memory
# constrained, for example, by running the training script).
# export CUDA_VISIBLE_DEVICES=""

# Run inference to generate captions.
bazel-bin/im2txt/run_inference \
  --checkpoint_path=${CHECKPOINT_DIR} \
  --vocab_file=${VOCAB_FILE} \
  --input_files=${IMAGE_DIR}
